USE ROLE ACCOUNTADMIN;
CREATE DATABASE IF NOT EXISTS RETAIL_MERCHANDISING DATA_RETENTION_TIME_IN_DAYS = 7;
CREATE SCHEMA IF NOT EXISTS RETAIL_MERCHANDISING.RAW DATA_RETENTION_TIME_IN_DAYS = 3;
CREATE SCHEMA IF NOT EXISTS RETAIL_MERCHANDISING.CURATED DATA_RETENTION_TIME_IN_DAYS = 7;
CREATE SCHEMA IF NOT EXISTS RETAIL_MERCHANDISING.AI DATA_RETENTION_TIME_IN_DAYS = 14;
CREATE SCHEMA IF NOT EXISTS RETAIL_MERCHANDISING.ML DATA_RETENTION_TIME_IN_DAYS = 14;
CREATE SCHEMA IF NOT EXISTS RETAIL_MERCHANDISING.SEARCH;
CREATE SCHEMA IF NOT EXISTS RETAIL_MERCHANDISING.APP;
CREATE WAREHOUSE IF NOT EXISTS WH_MERCHANDISING WAREHOUSE_SIZE = 'MEDIUM' AUTO_SUSPEND = 120 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
