USE ROLE ACCOUNTADMIN;
USE DATABASE RETAIL_MERCHANDISING;
USE WAREHOUSE WH_MERCHANDISING;

CREATE STAGE IF NOT EXISTS RETAIL_MERCHANDISING.RAW.COMPETITOR_FEEDS_STAGE
    URL = 's3://sg-retail-demos-2026/merchandising/competitor-feeds/'
    STORAGE_INTEGRATION = RETAIL_DEMOS_S3_INTEGRATION
    FILE_FORMAT = (TYPE = 'JSON' STRIP_OUTER_ARRAY = TRUE);
